<?php
    namespace Config;
    
    use \Framework\Web\Web as Web;

/**
 * Generated by framework installer - Wed, 19 Oct 2016 11:34:07 +0100
 */
    class Config
    {
	const BASEDNAME	= '/testfw';
	const DBHOST	= 'localhost';
	const DB	= 'testfw';
	const DBUSER	= 'testfw';
	const DBPW	= 'testfw';
	const SITENAME	= 'testfw';
	const SITEURL	= 'http://catless.ncl.ac.uk/testfw';
	const SITENOREPLY	= 'noreply@foo.com';
	const SYSADMIN	= 'lindsay.marshall@ncl.ac.uk';
	const DBOP	= '=';
	const UPUBLIC	= FALSE;
	const UPRIVATE	= TRUE;

	public static function setup()
	{
	    Web::getinstance()->addheader([
		'Date'			=> gmstrftime('%b %d %Y %H:%M:%S', time()),
		'Window-target'		=> '_top',	# deframes things
		'X-Frame-Options'	=> 'DENY',	# deframes things
		'Content-Language'	=> 'en',
		'Vary'			=> 'Accept-Encoding',
	    ]);
	}
    }
?>