<?php
    namespace Config;
/**
 * Generated by framework installer - Mon, 09 Jul 2018 13:50:57 +0100
*/
    class Config
    {
        public const BASEDNAME	= '/xxx';
        public const SESSIONNAME	= 'PSIxx';
        public const PUTORPATCH    = 'PATCH';
        public const DBTYPE	= 'mysql';
        public const DBHOST	= 'xx';
        public const DB	= 'xx';
        public const DBUSER	= 'xxx';
        public const DBPW	= 'xxx';
        public const SITENAME	= 'xxx';
        public const SITENOREPLY	= 'noreply@y.z';
        public const SYSADMIN	= 'x@y.z';
        public const DBRX	= FALSE;
        public const REGISTER  = FALSE;
        public const UPUBLIC	= FALSE;
        public const UPRIVATE	= FALSE;
        public const USEPHPM	= FALSE;
        public const SMTPHOST = 'xxx';
        public const FWCONTEXT = 'Site';
        public const TESTCONTEXT = 'Test';
        public const ADMINROLE = 'Admin';
        public const DEVELROLE = 'Developer';
        public const TESTROLE = 'Tester';
        public const CONFIG = 'fwconfig';
        public const RECAPTCHA = 0;
        public const RECAPTCHAKEY = 'aaaaaa';
        public const RECAPTCHASECRET = 'aaaaaa';
        public const SMTPPORT = 1;
        public const PROTOCOL = 'tls';
        public const SMTPUSER = 'user';
        public const SMTPPW = 'pw';

        public static function setup() : void
        {
            \Framework\Web\Web::getinstance()->addheader([
                'Date'              => gmstrftime('%b %d %Y %H:%M:%S', time()),
                'Window-target'     => '_top',      // deframes things
                'X-Frame-Options'	=> 'DENY',  // deframes things
                'Content-Language'	=> 'en',
                'Vary'              => 'Accept-Encoding',
                'X-Clacks-Overhead' => 'GNU Terry Pratchett',
                'X-Content-Type-Options' => 'nosniff',
                'X-XSS-Protection'       => '1; mode=block',
                'Strict-Transport-Security' => 'max-age=31536000',
            ]);
        }
/** @var array */
        public static $defaultCSP = [
                'default-src' => ["'self'"],
                'font-src' => ["'self'", '*.fontawesome.com'],
                'img-src' => ["'self'", "data:", "*.amuniversal.com"],
                'script-src' => ["'self'", "stackpath.bootstrapcdn.com", "cdnjs.cloudflare.com", "code.jquery.com"],
                'style-src' => ["'self'", "*.fontawesome.com", "stackpath.bootstrapcdn.com"],
        ];
    }
?>